import { useEffect, useMemo, useState } from 'react'
import {
  ActionIcon, Button, Container, Group, Image, LoadingOverlay, Modal, NumberInput, Pagination,
  Paper, Select, SimpleGrid, Stack, Table, Text, TextInput, Title,
} from '@mantine/core'
import { useMediaQuery } from '@mantine/hooks'
import { notifications } from '@mantine/notifications'
import dayjs from 'dayjs'
import { useDeleteExpense, useExpenses, usePeriods, useUpdateExpense } from '../hooks/useExpenses'
import { useDeletePhoto, useUploadPhoto } from '../hooks/useCreateExpense'
import { useOptions } from '../hooks/useOptions'
import PhotoInput, { type PhotoSelection } from '../components/PhotoInput'
import { getPhotoUrl } from '../services/expense'
import { formatCurrency } from '../utils/currency'
import { getErrorMessage } from '../utils/error'
import type { Expense } from '../types/expense'

const DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm'
const balanceColor = (value: number) => (value < 0 ? 'red' : undefined)

function HistoryPage() {
  const { data: periodsData, isPending: periodsLoading } = usePeriods(); const { data: options } = useOptions(); const [period, setPeriod] = useState<string | null>(null); const { data: expensesData, isPending: expensesLoading } = useExpenses(period); const isMobile = useMediaQuery('(max-width: 48em)')
  useEffect(() => { if (!period && periodsData?.periods.length) setPeriod(periodsData.periods[0]) }, [period, periodsData])
  const periods = useMemo(() => (periodsData?.periods ?? []).map((p) => ({ value: p, label: p })), [periodsData]); const expenses = expensesData?.expenses ?? []; const budgetOptions = useMemo(() => (options?.budgets ?? []).map((b) => ({ value: b.name, label: b.name })), [options])
  const [search, setSearch] = useState(''); const [budgetFilter, setBudgetFilter] = useState<string | null>(null); const [sortBy, setSortBy] = useState('waktu-desc'); const [viewingPhoto, setViewingPhoto] = useState<Expense | null>(null); const [page, setPage] = useState(1); const PAGE_SIZE = 15
  useEffect(() => { setPage(1) }, [search, budgetFilter, sortBy, period])
  const visibleExpenses = useMemo(() => { const q = search.trim().toLowerCase(); let list = expensesData?.expenses ?? []; if (q) list = list.filter((e) => e.name.toLowerCase().includes(q)); if (budgetFilter) list = list.filter((e) => e.budget === budgetFilter); const sorted = [...list]; switch (sortBy) { case 'waktu-asc': sorted.sort((a, b) => a.dateTime.localeCompare(b.dateTime)); break; case 'nominal-desc': sorted.sort((a, b) => b.amount - a.amount); break; case 'nominal-asc': sorted.sort((a, b) => a.amount - b.amount); break; default: sorted.sort((a, b) => b.dateTime.localeCompare(a.dateTime)) } return sorted }, [expensesData, search, budgetFilter, sortBy])
  const totalPages = Math.max(1, Math.ceil(visibleExpenses.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const pageExpenses = visibleExpenses.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE); const [editing, setEditing] = useState<Expense | null>(null); const [deleting, setDeleting] = useState<Expense | null>(null); const deleteExpense = useDeleteExpense()
  const handleDelete = () => { if (!deleting) return; deleteExpense.mutate(deleting.id, { onSuccess: () => { notifications.show({ title: 'Berhasil', message: 'Pengeluaran dihapus', color: 'green' }); setDeleting(null) }, onError: (error) => notifications.show({ title: 'Gagal', message: getErrorMessage(error), color: 'red' }) }) }
  const balanceOf = (name: string): number | undefined => options?.budgets.find((b) => b.name === name)?.balance; const deletingBalance = deleting ? balanceOf(deleting.budget) : undefined; const projectedDeleteBalance = deletingBalance !== undefined && deleting ? deletingBalance + deleting.amount : undefined
  return <Container size="md" py="lg"><Stack gap="lg"><Group justify="space-between" align="flex-end"><div><Text size="sm" c="blue" fw={700} mb={4}>TRANSACTIONS</Text><Title order={1} size="clamp(1.65rem, 5vw, 2.1rem)">Riwayat Pengeluaran</Title><Text c="dimmed" mt={5}>Lihat dan kelola semua pengeluaran kamu.</Text></div><Select w={{ base: 150, sm: 190 }} placeholder={periodsLoading ? 'Memuat...' : 'Pilih periode'} data={periods} value={period} onChange={setPeriod} searchable size="sm" aria-label="Periode" /></Group>
    {period && <SimpleGrid cols={{ base: 1, sm: 3 }} spacing="xs"><TextInput placeholder="Cari nama..." value={search} onChange={(e) => setSearch(e.currentTarget.value)} /><Select placeholder="Semua budget" data={budgetOptions} value={budgetFilter} onChange={setBudgetFilter} clearable searchable /><Select placeholder="Urutkan" data={[{ value: 'waktu-desc', label: 'Waktu terbaru' }, { value: 'waktu-asc', label: 'Waktu terlama' }, { value: 'nominal-desc', label: 'Nominal terbesar' }, { value: 'nominal-asc', label: 'Nominal terkecil' }]} value={sortBy} onChange={(v) => setSortBy(v ?? 'waktu-desc')} /></SimpleGrid>}
    <Paper withBorder p={{ base: 'sm', sm: 'lg' }} radius="xl" pos="relative"><LoadingOverlay visible={expensesLoading && !!period} zIndex={1000} overlayProps={{ radius: 'lg', blur: 1 }} />{expenses.length === 0 ? <Text c="dimmed" ta="center" py="lg">{period ? 'Tidak ada pengeluaran pada periode ini.' : 'Pilih periode untuk melihat pengeluaran.'}</Text> : visibleExpenses.length === 0 ? <Text c="dimmed" ta="center" py="lg">Tidak ada hasil yang cocok dengan filter.</Text> : isMobile ? <Stack gap="sm">{pageExpenses.map((expense) => <Paper key={expense.id} withBorder p="sm" radius="md"><Group justify="space-between" mb={4} wrap="nowrap" align="flex-start"><Text fw={600} style={{ wordBreak: 'break-word' }}>{expense.name}</Text><Text fw={700} ff="monospace" style={{ whiteSpace: 'nowrap' }}>{formatCurrency(expense.amount)}</Text></Group><Group justify="space-between" mb="xs"><Text size="sm" c="dimmed">{dayjs(expense.dateTime).format(DATE_TIME_FORMAT)}</Text><Text size="sm" c="dimmed">{expense.budget}</Text></Group><Group justify="flex-end" gap="xs">{expense.hasPhoto && <ActionIcon variant="subtle" color="gray" onClick={() => setViewingPhoto(expense)} aria-label="Lihat foto">📷</ActionIcon>}<ActionIcon variant="subtle" color="blue" onClick={() => setEditing(expense)} aria-label="Edit">✎</ActionIcon><ActionIcon variant="subtle" color="red" onClick={() => setDeleting(expense)} aria-label="Hapus">🗑</ActionIcon></Group></Paper>)}</Stack> : <Table highlightOnHover><Table.Thead><Table.Tr><Table.Th>Waktu</Table.Th><Table.Th>Name</Table.Th><Table.Th>Budget</Table.Th><Table.Th ta="right">Nominal</Table.Th><Table.Th ta="right">Aksi</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{pageExpenses.map((expense) => <Table.Tr key={expense.id}><Table.Td>{dayjs(expense.dateTime).format(DATE_TIME_FORMAT)}</Table.Td><Table.Td>{expense.name}</Table.Td><Table.Td>{expense.budget}</Table.Td><Table.Td ta="right">{formatCurrency(expense.amount)}</Table.Td><Table.Td ta="right"><Group gap="xs" justify="flex-end" wrap="nowrap">{expense.hasPhoto && <ActionIcon variant="subtle" color="gray" onClick={() => setViewingPhoto(expense)} aria-label="Lihat foto">📷</ActionIcon>}<ActionIcon variant="subtle" color="blue" onClick={() => setEditing(expense)} aria-label="Edit">✎</ActionIcon><ActionIcon variant="subtle" color="red" onClick={() => setDeleting(expense)} aria-label="Hapus">🗑</ActionIcon></Group></Table.Td></Table.Tr>)}</Table.Tbody></Table>}</Paper>
    {totalPages > 1 && <Group justify="center"><Pagination value={safePage} onChange={setPage} total={totalPages} /></Group>}
    {editing && <EditExpenseModal expense={editing} onClose={() => setEditing(null)} />}
    <Modal opened={!!viewingPhoto} onClose={() => setViewingPhoto(null)} title={viewingPhoto?.name ?? viewingPhoto?.photoName ?? 'Invoice'} size="md" centered>{viewingPhoto && (viewingPhoto.photoType === 'pdf' ? <Stack align="center"><Text fz={48}>📄</Text><Button component="a" href={getPhotoUrl(viewingPhoto.id)} target="_blank" variant="light">Buka PDF</Button></Stack> : <Image src={getPhotoUrl(viewingPhoto.id)} alt={viewingPhoto?.photoName ?? viewingPhoto?.name ?? 'Invoice'} fit="contain" mah="70vh" />)}</Modal>
    <Modal opened={!!deleting} onClose={() => setDeleting(null)} title="Hapus pengeluaran" centered><Text>Yakin ingin menghapus "{deleting?.name}" sebesar {deleting ? formatCurrency(deleting.amount) : ''}?</Text>{deleting && projectedDeleteBalance !== undefined && <Paper withBorder p="sm" radius="md" mt="md"><Stack gap="4"><Group justify="space-between"><Text size="sm" c="dimmed">Saldo saat ini</Text><Text>{formatCurrency(deletingBalance ?? 0)}</Text></Group><Group justify="space-between"><Text size="sm" c="dimmed">Dikembalikan</Text><Text>+{formatCurrency(deleting.amount)}</Text></Group><Group justify="space-between"><Text fw={500}>Saldo nanti</Text><Text fw={700} c={balanceColor(projectedDeleteBalance)}>{formatCurrency(projectedDeleteBalance)}</Text></Group></Stack></Paper>}<Group justify="flex-end" mt="lg"><Button variant="default" onClick={() => setDeleting(null)}>Batal</Button><Button color="red" loading={deleteExpense.isPending} onClick={handleDelete}>Hapus</Button></Group></Modal>
  </Stack></Container>
}

function EditExpenseModal({ expense, onClose }: { expense: Expense; onClose: () => void }) {
  const { data: options } = useOptions(); const updateExpense = useUpdateExpense(); const uploadPhoto = useUploadPhoto(); const deletePhoto = useDeletePhoto(); const [dateTime, setDateTime] = useState(expense.dateTime); const [name, setName] = useState(expense.name); const [budget, setBudget] = useState<string | null>(expense.budget); const [amount, setAmount] = useState<string | number>(expense.amount); const [description, setDescription] = useState(expense.description ?? ''); const [photo, setPhoto] = useState<PhotoSelection | null>(null); const [removePhoto, setRemovePhoto] = useState(false)
  const budgetOptions = useMemo(() => (options?.budgets ?? []).map((b) => ({ value: b.name, label: b.name })), [options]); const submitDisabled = name.trim() === '' || !budget || Number(amount) <= 0 || updateExpense.isPending
  const balanceOf = (n: string): number | undefined => options?.budgets.find((b) => b.name === n)?.balance; const oldAmount = expense.amount; const newAmount = Number(amount); const sameBudget = budget === expense.budget; const editPreview = !!budget && newAmount > 0; const oldBalance = balanceOf(expense.budget); const newBudgetBalance = budget ? balanceOf(budget) : undefined; const projectedSameBudget = oldBalance !== undefined && sameBudget ? oldBalance + oldAmount - newAmount : undefined; const projectedOldBudget = oldBalance !== undefined && !sameBudget ? oldBalance + oldAmount : undefined; const projectedNewBudget = newBudgetBalance !== undefined && !sameBudget ? newBudgetBalance - newAmount : undefined
  const handleSubmit = () => updateExpense.mutate({ id: expense.id, request: { dateTime, name: name.trim(), budget: budget ?? '', amount: Number(amount), description: description.trim() === '' ? undefined : description.trim() } }, { onSuccess: async () => { if (removePhoto && expense.hasPhoto) deletePhoto.mutate(expense.id); if (photo?.kind === 'new') uploadPhoto.mutate({ id: expense.id, file: photo.file }); notifications.show({ title: 'Berhasil', message: 'Pengeluaran diperbarui', color: 'green' }); onClose() }, onError: (error) => notifications.show({ title: 'Gagal', message: getErrorMessage(error), color: 'red' }) })
  return <Modal opened onClose={onClose} title="Edit pengeluaran" centered><Stack><TextInput label="Tanggal & waktu" value={dateTime} onChange={(e) => setDateTime(e.currentTarget.value)} /><TextInput label="Nama" value={name} onChange={(e) => setName(e.currentTarget.value)} /><Select label="Budget" data={budgetOptions} value={budget} onChange={setBudget} searchable /><NumberInput label="Nominal" value={amount} onChange={setAmount} min={0} /><TextInput label="Deskripsi" value={description} onChange={(e) => setDescription(e.currentTarget.value)} /><PhotoInput value={photo} onChange={setPhoto} dateTime={dateTime} />{expense.hasPhoto && <Button variant={removePhoto ? 'filled' : 'light'} color="red" onClick={() => setRemovePhoto((v) => !v)}>{removePhoto ? 'Foto akan dihapus' : 'Hapus foto'}</Button>}{editPreview && <Paper withBorder p="sm"><Stack gap={4}><Text size="sm" fw={700}>Preview saldo</Text>{sameBudget ? <Group justify="space-between"><Text size="sm" c="dimmed">Saldo setelah edit</Text><Text c={balanceColor(projectedSameBudget ?? 0)}>{projectedSameBudget !== undefined ? formatCurrency(projectedSameBudget) : '-'}</Text></Group> : <><Group justify="space-between"><Text size="sm" c="dimmed">Budget lama</Text><Text>{projectedOldBudget !== undefined ? formatCurrency(projectedOldBudget) : '-'}</Text></Group><Group justify="space-between"><Text size="sm" c="dimmed">Budget baru</Text><Text>{projectedNewBudget !== undefined ? formatCurrency(projectedNewBudget) : '-'}</Text></Group></>}</Stack></Paper>}<Group justify="flex-end"><Button variant="default" onClick={onClose}>Batal</Button><Button onClick={handleSubmit} disabled={submitDisabled} loading={updateExpense.isPending}>Simpan</Button></Group></Stack></Modal>
}
export default HistoryPage