server:
  port: ${PORT:8080}

spring:
  application:
    name: expense-tracker-backend
  config:
    import: optional:file:./.env
  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}

logging:
  structured:
    format:
      console: ecs
